services:
  user-db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    env_file:
      - ./.env.shared
      - ./user-service/.env
    depends_on:
      - user-db

  product-db:
    image: postgres:15
    container_name: product_db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  product-service:
    build:
      context: ./product-service
    container_name: product_service
    env_file:
      - ./.env.shared
      - ./product-service/.env
    depends_on:
      - product-db

  cart-db:
    image: postgres:15
    container_name: cart_db
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - cart_data:/var/lib/postgresql/data

  cart-service:
    build:
      context: ./cart-service
    container_name: cart_service
    env_file:
      - ./.env.shared
      - ./cart-service/.env
    depends_on:
      - cart-db

  order-db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
    container_name: order_service
    env_file:
      - ./.env.shared
      - ./order-service/.env
    depends_on:
      - order-db

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    env_file:
      - ./.env.shared
      - ./gateway-service/.env
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
    ports:
      - "8080:8080"

volumes:
  user_data:
  product_data:
  cart_data:
  order_data:
