server:
  port: 8761

spring:
  application:
    name: "eurekaserver"
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

