services:
  network-deploy-service:
    networks:
      - ecommerce-network

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 2G

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URI: http://configserver:8888

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
